### ISSUE TITLE
Why didn't my joshuto work

### ISSUE THREAD

**Issue by TaterDoge** [is0n/tui-nvim#3]
But my ranger works

  function Ranger()
    require("tui-nvim"):new({
      -- write selected files to '/tmp/tui-nvim'
      cmd = "ranger --choosefiles=/tmp/tui-nvim --selectfile=" .. vim.fn.fnameescape(vim.fn.expand("%:p")),
    })
  end

  function Joshuto()
    require("tui-nvim"):new({
      -- write selected files to '/tmp/tui-nvim'
      cmd = "joshuto --choosefiles=/tmp/tui-nvim --selectfile=" .. vim.fn.fnameescape(vim.fn.expand("%:p")),
    })
  end

  vim.cmd([[ command! Joshuto :lua Joshuto()<cr> ]])
  vim.cmd([[ command! Ranger :lua Ranger()<cr> ]])
  vim.api.nvim_set_keymap("n", "<leader>J", ":Joshuto<cr>", { noremap = true, silent = true })
  vim.api.nvim_set_keymap("n", "<leader>R", ":Ranger<cr>", { noremap = true, silent = true })

**Comment by Artexxx** [comment]
![Desktop_230808_2135](https://github.com/is0n/tui-nvim/assets/54672403/7073590a-0256-4da7-a944-de2488411998)

![Desktop_230808_2143](https://github.com/is0n/tui-nvim/assets/54672403/41a9aace-aef2-4419-9383-7739b164e012)
